### ISSUE TITLE
How to test with a different glass file?

### ISSUE THREAD

**Issue by ghost** [breathingcyborg/mediapipe-face-effects#2]
How do I test with a different glass file?
Also, I see a width of 1.4 hard-coded in glasses.js, how does it change with different 3d glass files?

**Comment by breathingcyborg** [comment]
@karnabhc 

Thanks for reporting the issue.

I've removed hard-coded value of 1.4. And added information in readme on how to prepare 3d glasses model. As long as model is prepared correctly it will work. 

In addition to that I've added a new glasses model, you can try it by editing `loadGlasses` function in `glasses.js` file.
```javascript
this.glasses = await loadModel( `${PUBLIC_PATH}/3d/glasses/scene.gltf` );
```

**Comment by ghost** [comment]
Thanks for the quick fix and reply, I will have a look with custom glass models
