### ISSUE TITLE
Can I get all the faces on the screen to wear glasses?

### ISSUE THREAD

**Issue by jayEwebs2022** [breathingcyborg/mediapipe-face-effects#3]
Can I get all the faces on the screen to wear glasses?      

I see [ maxNumFaces ] in landmarks_provider.js , 
I would like to know if this parameter will work

Thank you 👍

**Comment by breathingcyborg** [comment]
It doesn't work directly, but you can change a few things to make it work.

Currently landmarks_provider just takes the first face, you need to change that.
And you would need to change scene_manager to create multiple instances of glasses / face mesh.

**Comment by jayEwebs2022** [comment]
Thanks for your reply, I will give it a try.
