### ISSUE TITLE
Face morphing?

### ISSUE THREAD

**Issue by tjasmin111** [breathingcyborg/mediapipe-face-effects#4]
Interesting work. Do you have any ideas how can I do nose slimming effect? We have the facemesh, but not sure how to morph it to slim nose.

**Comment by breathingcyborg** [comment]
One way to do this is find nose region and apply bulge/pinch filter to it.

We already have the nose region. And the video is rendered as a material of three js plane. So what you could do is apply filter on nose region using libraries like glfx/pixi.js then update the material of three js plane. Here is demo link of the filter https://evanw.github.io/glfx.js/demo/#bulgePinch

**Comment by tjasmin111** [comment]
It works for simple cases, but what if we want to make the wing of the nose shorter? Like those makeup apps. They prob are not using pinch.
![e9Cqu](https://github.com/breathingcyborg/mediapipe-face-effects/assets/113141483/89bfc0c0-7b1d-4622-a3c4-c4254a8a3f11)

**Comment by breathingcyborg** [comment]
Totally agree. This use case would require writing a custom shader for morphing the nose region. The bulge/pinch filter does something similar, it uses a shader to negatively scale the roi.

**Comment by tjasmin111** [comment]
How easy is it to implement one?

**Comment by breathingcyborg** [comment]
Depends.

If you have experience with writing shaders, a simple implementation might take just a few hours.
However, for those of us who are new to shader development it could take a few days to learn how to write simple shaders.
